GYM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gymapp/', include('gymapp.urls')),
    path('manager/', include('manager.urls')),
    path('customerapp/', include('customerapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gymapp/urls.py
from django.urls import path

from . import views

app_name = "gymapp"
urlpatterns = [
    path("", views.index, name="index"),

    path("home/",views.home, name="home"),

    path("about/", views.about, name="about"),

    path("login/", views.login, name="login"),

    path("content/", views.content, name = "content"),

    path('register/', views.customer_registration, name='customer_registration'),

    # ex: /polls/5/
    path("<int:question_id>/", views.detail, name="detail"),

    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

gymapp/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class TestModel(models.Model):
    name = models.CharField(max_length=100)

templates/c_block.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>customer</title>
    <link rel="stylesheet" href="/static/css/manager.css">
</head>
<body>
    <!-- 网站的首页，所有网站的首页都叫index.html，因为服务器找首页都是找index.html -->
    <!-- 布局；从外到内，从上到下，从左到右 -->
    <!-- css：浮动/display;盒子模型;文字样式 -->

    <!--头部header:负责头部区域的样式，wrapper只负责版心效果  -->
    <div class="header wrapper">
        <h1>
            <a href="#"><img src="/static/img/logo.jpg" alt="标题"></a>
        </h1>
        <div class="nav">
            <ul>
                <li><a href="/customerapp">HOME</a></li>
                <li><a href="#">ABOUT</a></li>
                <li><a href="#">PROBLEM</a></li>
            </ul>
        </div>
        <!-- 搜索 -->
        <div class="search">
            <input type="text" placeholder="ENTER HERE">
            <button></button>
        </div>
        <div class="user">
            <img src="/static/img/users.jpg" alt="">
            <span>yuki</span>
            <!-- 轮播图 -->
        </div>
    </div>
    <div class="banner">
        <div class="wrapper">
            <div class="left">
                <ul>
                    <li><a href="/customerapp/coaches">Coaches<span>></span></a></li>
                    <li><a href="/customerapp/commodities">Commodities<span>></span></a></li>
                    <li><a href="/customerapp/courses">Courses<span>></span></a></li>
                    <li><a href="/customerapp/c_equipment">Equipment<span>></span></a></li>
                    <li><a href="/customerapp/c_cards">Cards<span>></span></a></li>
                    <li><a href="/customerapp/c_block">Block<span>></span></a></li>
                    <!--<li><a href="/customerapp/c_product">Product<span>></span></a></li>-->
                    <li><a href="/customerapp/c_order">Order<span>></span></a></li>
                    <li><a href="/customerapp/c_personal_info">Personal_info<span>></span></a></li>

                </ul>
            </div>
            <div class="right">
                <h2>MY SCHEDULE</h2>
                <div class="content">
                    <dl>
                        <span>Monday:&nbsp;</span><span class="ai">Course YOGA</span>
                        <dd>Alex</dd>
                    </dl>
                    <dl>
                        <span>Friday:&nbsp;</span><span class="ai">Course RUN</span>
                        <dd>Mark</dd>
                    </dl>
                    <dl>
                        <span>Sunday:&nbsp;</span><span class="ai">Course YOGA</span>
                        <dd>John</dd>
                    </dl>
                    <a href="#" class="more">ALL COURSE</a>
                </div>
            </div>
        </div>
    </div>
    <!-- 精品推荐 -->
   <!-- <div class="goods wrapper">
        <h2>RECOMMEND</h2>
        <ul>
            <li><a href="#">YOGA</a></li>
            <li><a href="#">RUN</a></li>
            <li><a href="#">Weight lifting</a></li>
            <li><a href="#">C</a></li>
            <li><a href="#">B</a></li>
            <li><a href="#">A</a></li>
        </ul>
        <a href="#" class="xingqu">CHANGE</a>
    </div> -->
    <!-- 精品课程 -->
    <div class="box wrapper">
        <div class="title">
        <h2>Where You Want Go?</h2>
            <a href="#">ALL</a>
        </div>
        <div class="content clearfix">
            <ui>
                {% for row in data %}


                <li>


                    <img src="data:image/jpeg;base64,{{ row.image }}" alt="" width="227" height="170">
                    <h3>{{ row.type}} </h3>
                    <p><span>{{ row.equipment }}</span> </p>

                </li>
                     {% endfor %}



            </ui>
        </div>
    </div>

</body>
</html>

templates/c_cards.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>customer</title>
    <link rel="stylesheet" href="/static/css/manager.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body>
    <script>
        const customer_id = "{{ customer_id }}";
    </script>

    <!-- Rest of the HTML code -->
    <div class="header wrapper">
        <h1>
            <a href="#"><img src="/static/img/logo.jpg" alt="标题"></a>
        </h1>
        <div class="nav">
            <ul>
                <li><a href="/customerapp">HOME</a></li>
                <li><a href="#">ABOUT</a></li>
                <li><a href="#">PROBLEM</a></li>
            </ul>
        </div>
        <!-- 搜索 -->
        <div class="search">
            <input type="text" placeholder="ENTER HERE">
            <button></button>
        </div>
    </div>
    <div class="banner">
        <div class="wrapper">
            <div class="left">
                <ul>
                    <li><a href="/customerapp/coaches">Coaches<span>></span></a></li>
                    <li><a href="/customerapp/commodities">Commodities<span>></span></a></li>
                    <li><a href="/customerapp/courses">Courses<span>></span></a></li>
                    <li><a href="/customerapp/c_equipment">Equipment<span>></span></a></li>
                    <li><a href="/customerapp/c_cards">Cards<span>></span></a></li>
                    <li><a href="/customerapp/c_block">Block<span>></span></a></li>
                    <!--<li><a href="/customerapp/c_product">Product<span>></span></a></li>-->
                    <li><a href="/customerapp/c_order">Order<span>></span></a></li>
                    <li><a href="/customerapp/c_personal_info">Personal_info<span>></span></a></li>

                </ul>
            </div>
            <div class="right">
                <h2>MY SCHEDULE</h2>
                <div class="content">
                    <dl>
                        <span>Monday:&nbsp;</span><span class="ai">Course YOGA</span>
                        <dd>Alex</dd>
                    </dl>
                    <dl>
                        <span>Friday:&nbsp;</span><span class="ai">Course RUN</span>
                        <dd>Mark</dd>
                    </dl>
                    <dl>
                        <span>Sunday:&nbsp;</span><span class="ai">Course YOGA</span>
                        <dd>John</dd>
                    </dl>
                    <a href="#" class="more">ALL COURSE</a>
                </div>
            </div>
        </div>
    </div>

    <div class="box wrapper">
        <div class="title">
        <h2>Do You Want Join Us?</h2>
            <a href="#">ALL</a>
        </div>
        <div>
            <h3>Junior Member - 6 months - $500</h3>
            <button class="join-member" data-member-type="junior">Join</button>
        </div>
        <div>
            <h3>Senior Member - 1 year - $1000</h3>
            <button class="join-member" data-member-type="senior">Join</button>
        </div>
    </div>

    <script>
function joinMembership(memberType) {
    const membershipData = {
        customer_id: customer_id,
        membership_type: memberType
    };

    $.ajax({
        url: '/customerapp/register_membership/',
        type: 'POST',
        data: JSON.stringify(membershipData),
        contentType: 'application/json; charset=utf-8',
        headers: {
            'X-CSRFToken': '{{ csrf_token }}'
        },
        success: function(response) {
            if (response.success) {
                alert('Successfully joined the membership!');
            } else {
                alert(response.error);
            }
        },
        error: function() {
            alert('An error occurred while processing your request. Please try again.');
        }
    });
}



        $(document).ready(function() {
            $('.join-member').click(function() {
                const memberType = $(this).data('member-type');
                joinMembership(memberType);
            });
        });


    </script>
</body>
</html>

templates/c_equipment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>customer</title>
    <link rel="stylesheet" href="/static/css/manager.css">
</head>
<body>
    <!-- 网站的首页，所有网站的首页都叫index.html，因为服务器找首页都是找index.html -->
    <!-- 布局；从外到内，从上到下，从左到右 -->
    <!-- css：浮动/display;盒子模型;文字样式 -->

    <!--头部header:负责头部区域的样式，wrapper只负责版心效果  -->
    <div class="header wrapper">
        <h1>
            <a href="#"><img src="/static/img/logo.jpg" alt="标题"></a>
        </h1>
        <div class="nav">
            <ul>
                <li><a href="/customerapp">HOME</a></li>
                <li><a href="#">ABOUT</a></li>
                <li><a href="#">PROBLEM</a></li>
            </ul>
        </div>
        <!-- 搜索 -->
        <div class="search">
            <input type="text" placeholder="ENTER HERE">
            <button></button>
        </div>
        <div class="user">
            <img src="/static/img/users.jpg" alt="">
            <span>yuki</span>
            <!-- 轮播图 -->
        </div>
    </div>
    <div class="banner">
        <div class="wrapper">
            <div class="left">
                <ul>
                    <li><a href="/customerapp/coaches">Coaches<span>></span></a></li>
                    <li><a href="/customerapp/commodities">Commodities<span>></span></a></li>
                    <li><a href="/customerapp/courses">Courses<span>></span></a></li>
                    <li><a href="/customerapp/c_equipment">Equipment<span>></span></a></li>
                    <li><a href="/customerapp/c_cards">Cards<span>></span></a></li>
                    <li><a href="/customerapp/c_block">Block<span>></span></a></li>
                    <!--<li><a href="/customerapp/c_product">Product<span>></span></a></li>-->
                    <li><a href="/customerapp/c_order">Order<span>></span></a></li>
                    <li><a href="/customerapp/c_personal_info">Personal_info<span>></span></a></li>

                </ul>
            </div>
            <div class="right">
                <h2>MY SCHEDULE</h2>
                <div class="content">
                    <dl>
                        <span>Monday:&nbsp;</span><span class="ai">Course YOGA</span>
                        <dd>Alex</dd>
                    </dl>
                    <dl>
                        <span>Friday:&nbsp;</span><span class="ai">Course RUN</span>
                        <dd>Mark</dd>
                    </dl>
                    <dl>
                        <span>Sunday:&nbsp;</span><span class="ai">Course YOGA</span>
                        <dd>John</dd>
                    </dl>
                    <a href="#" class="more">ALL COURSE</a>
                </div>
            </div>
        </div>
    </div>
    <!-- 精品推荐 -->
   <!-- <div class="goods wrapper">
        <h2>RECOMMEND</h2>
        <ul>
            <li><a href="#">YOGA</a></li>
            <li><a href="#">RUN</a></li>
            <li><a href="#">Weight lifting</a></li>
            <li><a href="#">C</a></li>
            <li><a href="#">B</a></li>
            <li><a href="#">A</a></li>
        </ul>
        <a href="#" class="xingqu">CHANGE</a>
    </div> -->
    <!-- 精品课程 -->
    <div class="box wrapper">
        <div class="title">
        <h2>EQUIPMENT WE HAVE</h2>
            <a href="#">ALL</a>
        </div>
        <div class="content clearfix">
            <ui>
                <li><a href="#">
                    <img src="/static/img/course1.jpg" alt="" width="227" height="180">
                    <h3>YOGA COURSE</h3>
                    <p><span>HIGH</span>-  1125 ARE NOW</p>
                    <!-- 定位的hot小图 -->
                    <img src="/static/img/hot.png" alt="" class="hot">
                </a></li>
                <li><a href="#">
                    <img src="/static/img/course1.png" alt="" width="227" height="180">
                    <h3>RUN</h3>
                    <p><span>NEW</span>-  1125 ARE NOW</p>
                    <img src="/static/img/new.png" alt="" class="hot">
                </a></li>
                <li><a href="#">
                    <img src="/static/img/course1.png" alt="" width="227" height="180">
                    <h3>RUN</h3>
                    <p><span>NEW</span>-  1125</p>
                    <img src="/static/img/hot.png" alt="" class="hot">
                </a></li>
                <li><a href="#">
                    <img src="./images/course1.png" alt="" width="227" height="180">
                    <h3>RUN</h3>
                    <p><span>HIGH</span>-  1125</p>
                    <img src="./images/hot.png" alt="" class="hot" >
                </a></li>
                <li><a href="#">
                    <img src="./images/course1.png" alt="" width="227" height="180">
                    <h3>RUN</h3>
                    <p><span>HIGH</span>-  1125</p>
                    <img src="./images/hot.png" alt="" class="hot" >
                </a></li>
                <li><a href="#">
                    <img src="./images/course1.png" alt="" width="227" height="180">
                    <h3>RUN</h3>
                    <p><span>HIGH</span>-  1125</p>
                    <img src="./images/hot.png" alt="" class="hot">
                </a></li>
                <li><a href="#">
                    <img src="./images/course1.png" alt="" width="227" height="180">
                    <h3>JOHN</h3>
                    <p><span>HIGH</span>-  1125</p>
                    <img src="./images/hot.png" alt="" class="hot" >
                </a></li>
                <li><a href="#">
                    <img src="./images/course1.png" alt="" width="227" height="180">
                    <h3>ALEX</h3>
                    <p><span>HIGH</span>-  1125</p>
                </a></li>
                <li><a href="#">
                    <img src="./images/course1.png" alt="" width="227" height="180">
                    <h3>ABC</h3>
                    <p><span>HIGH</span>-  1125</p>
                </a></li>
                <li><a href="#">
                    <img src="./images/course1.png" alt="" width="227" height="180">
                    <h3>VBN</h3>
                    <p><span>HIGH</span>-  1125</p>
                </a></li>

            </ui>
        </div>
    </div>

</body>
</html>

templates/c_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>customer</title>
    <style type="text/css">
        #fukuan{
            position: absolute;
            left: 500px;
            top: 100px;

        }

    </style>
</head>
<body>
<img src="/static/img/pay.jpg" alt="" width="700" height="1200" id="fukuan">

</body>
</html>

templates/login.html
{% extends 'navigation.html' %}
{% block body %}
{% load static %}
{% ifequal error "no" %}
<script>
    alert('Logged In Successfully');
    window.location=("{% url 'home' %}")
</script>
{% endifequal %}
{% ifequal error "yes" %}
<script>
    alert('Invalid Login Credentials, Try Again');
</script>
{% endifequal %}

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-t-80 ">
            <form class="login100-form validate-form pt-0" action="" method="post">
                {% csrf_token %}
                <div class="login100-form-avatar">
                    <img src="{% static 'images/gym-avatar.jpg' %}" alt="AVATAR">
                </div>

                <span class="login100-form-title p-t-20 p-b-45 mt-5 mb-4">
                </span>

                <div class="wrap-input100 validate-input m-b-10 mb-3" data-validate = "Username is required">
                    <input class="input100" type="text" name="uname" placeholder="Username">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-user"></i>
                    </span>
                </div>

                <div class="wrap-input100 validate-input m-b-10 mb-3" data-validate = "Password is required">
                    <input class="input100" type="password" name="pwd" placeholder="Password">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-lock"></i>
                    </span>
                </div>

                <div class="wrap-input100 m-b-10 mb-3">
                    <label>
                        <input type="radio" name="user_type" value="manager" required> Manager
                    </label>
                    <label>
                        <input type="radio" name="user_type" value="customer" required> Customer
                    </label>
                </div>

                <div id="registration-link" class="text-center w-full" style="display: none;">
                    <a href="{% url 'gymapp:customer_registration' %}" class="txt1">Register as Customer</a>
                </div>

                <div class="container-login100-form-btn p-t-10">
                    <button class="login100-form-btn">
                        Login
                    </button>
                </div>

                <div class="text-center w-full p-t-25 p-b-230">
                    <a href="#" class="txt1">
                        Forgot Username / Password?
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    document.querySelectorAll('input[name="user_type"]').forEach(function (radio) {
        radio.addEventListener('change', function () {
            if (this.value === 'customer') {
                document.getElementById('registration-link').style.display = 'block';
            } else {
                document.getElementById('registration-link').style.display = 'none';
            }
        });
    });
</script>

{% endblock %}

templates/navigation.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <title>Gym Management</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <!--font awesome cdns start here-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--font awesome cdns start here-->


    <!-- login page link start here-->
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{% static 'images/ico/favicon.ico' %}" />

        <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!--=============================================================================================== -->
    <!-- login page link ends here-->

    <!--Index page css start here-->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet"> -->
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'images/ico/favicon.ico' %}">
    <!--Index page css ends here-->

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css">
    <style>
        {% block css %} {% endblock %}
   </style>


</head>

<nav class="navbar navbar-expand-md navbar-fixed-top bg-dark justify-content-center">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#abc"><span
                class="navbar-toggler-icon"></span></button>
        <a class="navbar-brand" href="#"><img class="" style="width: 200px; height:30px; margin-top:auto; border-radius:10px" src="{% static 'images/logo2.png' %}" alt="logo"></a>
        <!-- <a href="" class="navbar-brand navbar-collapse collapse">GYM MANAGEMENT SYSTEM</a> -->
        <div class="collapse navbar-collapse navbar-right">
            <ul class="nav navbar-nav">
                <li class="scroll active"><a href="{% url 'gymapp:home' %}">Home</a></li>
                <li class="scroll"><a href="{% url 'gymapp:about' %}">About</a></li>
                <li class="scroll"><a href="{% url 'gymapp:login' %}">Login</a></li>
                <li class="scroll"><a href="{% url 'gymapp:content' %}">Contact</a></li>
            </ul>
            <ul class="nav navbar-nav">
                {% if request.user.is_staff %}
                <li class="scroll dropdown active">
                    <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">Enquiry</a>
                    <div class="dropdown-menu nav-link">
                        <a href="/add_enquiry" class="dropdown-item">Add Enquiry</a>
                        <a href="/view_enquiry" class="dropdown-item">View Enquiry</a>
                    </div>
                </li>
                <li class="scroll dropdown">
                    <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">Plan</a>
                    <div class="dropdown-menu nav-link">
                        <a href="/add_plan" class="dropdown-item">Add Plan</a>
                        <a href="/view_plan" class="dropdown-item">View Plan</a>
                    </div>
                </li>
                <li class="scroll dropdown">
                    <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">Equipment</a>
                    <div class="dropdown-menu nav-link">
                        <a href="/add_equipment" class="dropdown-item">Add Equipment</a>
                        <a href="/view_equipment" class="dropdown-item">View Equipment</a>
                    </div>
                </li>
                <li class="scroll dropdown">
                    <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">Member</a>
                    <div class="dropdown-menu nav-link">
                        <a href="/add_member" class="dropdown-item">Add Member</a>
                        <a href="/view_member" class="dropdown-item">View Member</a>
                    </div>
                </li>
                <li class="scroll"><a href="/logout">Logout</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <!--/.container-->
</nav>
<!--/nav-->

<body>
    {% block body %}

    {% endblock %}
</body>

{% block footer%}
{% endblock %}
<!--/#footer-->
<!-- Data table Cdn start here -->
<script>
    $(document).ready(function () {
        $('#example').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copyHtml5',
                'excelHtml5',
                'csvHtml5',
                'pdfHtml5'
            ]
        });
    });
</script>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>
<!-- Data table Cdn ends here-->

<!--index page js link start here-->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/mousescroll.js' %}"></script>
<script src="{% static 'js/smoothscroll.js' %}"></script>
<script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
<script src="{% static 'js/jquery.isotope.min.js' %}"></script>
<script src="{% static 'js/jquery.inview.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/custom-scripts.js' %}"></script>
<!--index page js link ends here-->


<!--bootstrap js cdn start here-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<!--bootstrap js cdn start here-->
</html>

templates/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'gymapp:detail' question.id %}">Vote again?</a>